package classproject;

import java.awt.Component;
import javax.swing.Icon;
import javax.swing.JOptionPane;

/**
 * This class contains all necessary variables and methods for GUI presentation.
 * 
 */
public class Menu extends javax.swing.JFrame { 
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        //Group radio buttons and declare which ones are set as default
        mozzarrellaRadioButton.setSelected(true);
        cheeseButtonGroup.add(mozzarrellaRadioButton);
        cheeseButtonGroup.add(fetaRadioButton);
        cheeseButtonGroup.add(ricottaRadioButton);
        kidsRadioButton.setSelected(true);
        sizeButtonGroup.add(kidsRadioButton);
        sizeButtonGroup.add(regularRadioButton);
        sizeButtonGroup.add(massiveRadioButton);
        boringRadioButton.setSelected(true);
        crustButtonGroup.add(boringRadioButton);
        crustButtonGroup.add(cheesyRadioButton);
        crustButtonGroup.add(crazyRadioButton);
        pickupRadioButton.setSelected(true);
        deliveryButtonGroup.add(pickupRadioButton);
        deliveryButtonGroup.add(deliveryRadioButton);
        
        //Configure the two textAreas and display the availableToppings array from main()
        this.availableToppingTextArea.setEditable(false);
        this.availableToppingTextArea.setWrapStyleWord(true);
        for(String i : ClassProject.availableToppings){
           this.availableToppingTextArea.append(" "+i+"\n");
        }
        this.orderReviewTextArea.setEditable(false);
        this.orderReviewTextArea.setWrapStyleWord(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cheeseButtonGroup = new javax.swing.ButtonGroup();
        sizeButtonGroup = new javax.swing.ButtonGroup();
        crustButtonGroup = new javax.swing.ButtonGroup();
        deliveryButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        addToppingButton = new javax.swing.JButton();
        recipeLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        availableToppingTextArea = new javax.swing.JTextArea();
        availableToppingsLabel = new javax.swing.JLabel();
        addToppingTextField = new javax.swing.JTextField();
        addToppingLabel = new javax.swing.JLabel();
        mozzarrellaRadioButton = new javax.swing.JRadioButton();
        fetaRadioButton = new javax.swing.JRadioButton();
        ricottaRadioButton = new javax.swing.JRadioButton();
        kidsRadioButton = new javax.swing.JRadioButton();
        regularRadioButton = new javax.swing.JRadioButton();
        massiveRadioButton = new javax.swing.JRadioButton();
        boringRadioButton = new javax.swing.JRadioButton();
        cheesyRadioButton = new javax.swing.JRadioButton();
        crazyRadioButton = new javax.swing.JRadioButton();
        OrderButton = new javax.swing.JButton();
        pickupRadioButton = new javax.swing.JRadioButton();
        deliveryRadioButton = new javax.swing.JRadioButton();
        cheesesLabel = new javax.swing.JLabel();
        sizesLabel = new javax.swing.JLabel();
        crustLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderReviewTextArea = new javax.swing.JTextArea();
        titleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ClassProject Menu");

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        addToppingButton.setFont(new java.awt.Font("Cooper Black", 0, 16)); // NOI18N
        addToppingButton.setForeground(new java.awt.Color(0, 51, 255));
        addToppingButton.setText("Add");
        addToppingButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addToppingButtonMouseClicked(evt);
            }
        });

        recipeLabel.setBackground(new java.awt.Color(0, 51, 255));
        recipeLabel.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        recipeLabel.setForeground(new java.awt.Color(255, 255, 102));
        recipeLabel.setText("Review of order");

        availableToppingTextArea.setBackground(new java.awt.Color(204, 204, 204));
        availableToppingTextArea.setColumns(20);
        availableToppingTextArea.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 24)); // NOI18N
        availableToppingTextArea.setForeground(new java.awt.Color(0, 51, 255));
        availableToppingTextArea.setRows(5);
        jScrollPane1.setViewportView(availableToppingTextArea);

        availableToppingsLabel.setBackground(new java.awt.Color(0, 51, 255));
        availableToppingsLabel.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        availableToppingsLabel.setForeground(new java.awt.Color(255, 255, 102));
        availableToppingsLabel.setText("Available Toppings");

        addToppingTextField.setBackground(new java.awt.Color(204, 204, 204));
        addToppingTextField.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        addToppingTextField.setForeground(new java.awt.Color(0, 51, 255));

        addToppingLabel.setBackground(new java.awt.Color(0, 51, 255));
        addToppingLabel.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        addToppingLabel.setForeground(new java.awt.Color(255, 255, 102));
        addToppingLabel.setText("Add a topping - $.99");

        mozzarrellaRadioButton.setBackground(new java.awt.Color(0, 51, 255));
        mozzarrellaRadioButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        mozzarrellaRadioButton.setForeground(new java.awt.Color(255, 153, 51));
        mozzarrellaRadioButton.setText("Mozzarrella");
        mozzarrellaRadioButton.setToolTipText("");

        fetaRadioButton.setBackground(new java.awt.Color(0, 51, 255));
        fetaRadioButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        fetaRadioButton.setForeground(new java.awt.Color(255, 153, 51));
        fetaRadioButton.setText("Feta");

        ricottaRadioButton.setBackground(new java.awt.Color(0, 51, 255));
        ricottaRadioButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        ricottaRadioButton.setForeground(new java.awt.Color(255, 153, 51));
        ricottaRadioButton.setSelected(true);
        ricottaRadioButton.setText("Ricotta");

        kidsRadioButton.setBackground(new java.awt.Color(0, 51, 255));
        kidsRadioButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        kidsRadioButton.setForeground(new java.awt.Color(255, 153, 51));
        kidsRadioButton.setText("Kids - $9.99");

        regularRadioButton.setBackground(new java.awt.Color(0, 51, 255));
        regularRadioButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        regularRadioButton.setForeground(new java.awt.Color(255, 153, 51));
        regularRadioButton.setText("Regular - $12.99");

        massiveRadioButton.setBackground(new java.awt.Color(0, 51, 255));
        massiveRadioButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        massiveRadioButton.setForeground(new java.awt.Color(255, 153, 51));
        massiveRadioButton.setText("Massive - $14.99");

        boringRadioButton.setBackground(new java.awt.Color(0, 51, 255));
        boringRadioButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        boringRadioButton.setForeground(new java.awt.Color(255, 153, 51));
        boringRadioButton.setText("Boring");

        cheesyRadioButton.setBackground(new java.awt.Color(0, 51, 255));
        cheesyRadioButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        cheesyRadioButton.setForeground(new java.awt.Color(255, 153, 51));
        cheesyRadioButton.setText("Cheesy - $1.75");

        crazyRadioButton.setBackground(new java.awt.Color(0, 51, 255));
        crazyRadioButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        crazyRadioButton.setForeground(new java.awt.Color(255, 153, 51));
        crazyRadioButton.setText("Crazy - $2.50");

        OrderButton.setFont(new java.awt.Font("Cooper Black", 0, 16)); // NOI18N
        OrderButton.setForeground(new java.awt.Color(0, 51, 255));
        OrderButton.setText("Order");
        OrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderButtonActionPerformed(evt);
            }
        });

        pickupRadioButton.setBackground(new java.awt.Color(0, 51, 255));
        pickupRadioButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        pickupRadioButton.setForeground(new java.awt.Color(255, 153, 51));
        pickupRadioButton.setText("PickUp");

        deliveryRadioButton.setBackground(new java.awt.Color(0, 51, 255));
        deliveryRadioButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        deliveryRadioButton.setForeground(new java.awt.Color(255, 153, 51));
        deliveryRadioButton.setText("Delivery");

        cheesesLabel.setBackground(new java.awt.Color(0, 51, 255));
        cheesesLabel.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        cheesesLabel.setForeground(new java.awt.Color(255, 255, 102));
        cheesesLabel.setText("Cheeses");

        sizesLabel.setBackground(new java.awt.Color(0, 51, 255));
        sizesLabel.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        sizesLabel.setForeground(new java.awt.Color(255, 255, 102));
        sizesLabel.setText("Sizes");

        crustLabel.setBackground(new java.awt.Color(0, 51, 255));
        crustLabel.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        crustLabel.setForeground(new java.awt.Color(255, 255, 102));
        crustLabel.setText("Crust");

        orderReviewTextArea.setBackground(new java.awt.Color(204, 204, 204));
        orderReviewTextArea.setColumns(20);
        orderReviewTextArea.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        orderReviewTextArea.setForeground(new java.awt.Color(0, 51, 255));
        orderReviewTextArea.setRows(5);
        jScrollPane2.setViewportView(orderReviewTextArea);

        titleLabel.setBackground(new java.awt.Color(0, 51, 255));
        titleLabel.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 153, 51));
        titleLabel.setText("Build Your Favorite Pizza");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(recipeLabel)
                        .addGap(117, 117, 117))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fetaRadioButton)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(mozzarrellaRadioButton)
                                                    .addComponent(ricottaRadioButton)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(14, 14, 14)
                                                        .addComponent(cheesesLabel)))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(85, 85, 85)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(kidsRadioButton)
                                                            .addComponent(regularRadioButton)
                                                            .addComponent(massiveRadioButton)))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(109, 109, 109)
                                                        .addComponent(sizesLabel)))
                                                .addGap(64, 64, 64)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cheesyRadioButton)
                                                    .addComponent(boringRadioButton)
                                                    .addComponent(crazyRadioButton)
                                                    .addComponent(crustLabel)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(71, 71, 71)
                                                .addComponent(OrderButton))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(pickupRadioButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(deliveryRadioButton))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(addToppingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(addToppingButton))
                                            .addComponent(addToppingLabel))
                                        .addGap(76, 76, 76)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(titleLabel)))
                        .addGap(16, 16, 16)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(availableToppingsLabel)
                        .addGap(46, 46, 46)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel)
                    .addComponent(availableToppingsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cheesesLabel)
                            .addComponent(sizesLabel)
                            .addComponent(crustLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boringRadioButton)
                            .addComponent(kidsRadioButton)
                            .addComponent(mozzarrellaRadioButton))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cheesyRadioButton)
                            .addComponent(regularRadioButton)
                            .addComponent(fetaRadioButton))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(crazyRadioButton)
                            .addComponent(massiveRadioButton)
                            .addComponent(ricottaRadioButton))
                        .addGap(18, 18, 18)
                        .addComponent(recipeLabel)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addComponent(addToppingLabel)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(addToppingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addToppingButton))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(deliveryRadioButton)
                                    .addComponent(pickupRadioButton))
                                .addGap(18, 18, 18)
                                .addComponent(OrderButton)
                                .addGap(25, 25, 25))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Handle the event for adding toppings; each topping is added to the PizzaOrder.toppings ArrayList
    // and then displayed in the GUI for the user to review
    private void addToppingButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addToppingButtonMouseClicked
        String text;
        text = this.addToppingTextField.getText();
        PizzaOrder.AddTopping(text.toLowerCase());
        this.addToppingTextField.setText(null);
        this.orderReviewTextArea.setText(null);
        this.orderReviewTextArea.append("HERE IS THE REVIEW OF YOUR ORDER:\n");
        this.orderReviewTextArea.append("Added Toppings: ");
        for(String i : PizzaOrder.toppings){
           this.orderReviewTextArea.append(i+",");
        }
    }//GEN-LAST:event_addToppingButtonMouseClicked

    private void OrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderButtonActionPerformed
        this.orderReviewTextArea.setText(null);
        Component frame = null;
        String orderName;
        Icon icon = null;
        orderName = (String)JOptionPane.showInputDialog(frame, "Enter Name:","Name for Order", JOptionPane.PLAIN_MESSAGE, icon, null, null);
        
        //Initialize the pre-set radio button option variables
        String cheese;
        String size;
        String crust;
        
        //Grab the values for the selected radio buttons and store them
        if(mozzarrellaRadioButton.isSelected()){
            cheese = mozzarrellaRadioButton.getText();
        }
        else if(fetaRadioButton.isSelected()){
            cheese = fetaRadioButton.getText();
        }
        else{
            cheese = ricottaRadioButton.getText();
        }
        
        if(kidsRadioButton.isSelected()){    
            size = kidsRadioButton.getText();
        }
        else if(regularRadioButton.isSelected()){
            size = regularRadioButton.getText();
        }
        else{
            size = massiveRadioButton.getText();
        }
        
        if(boringRadioButton.isSelected()){    
            crust = boringRadioButton.getText();
        }
        else if(cheesyRadioButton.isSelected()){
            crust = cheesyRadioButton.getText();
        }
        else{
            crust = crazyRadioButton.getText();
        }
        //Use the values to create a new PizzaOrder object called "pizza"
        PizzaOrder pizza = new PizzaOrder(size, crust, cheese, PizzaOrder.toppings);
        //Display the order in the review text area
        this.orderReviewTextArea.append("HERE IS THE REVIEW OF YOUR ORDER:\n");
        this.orderReviewTextArea.append("Name for order: "+orderName+"\n");
        this.orderReviewTextArea.append("Cheese: "+pizza.get_cheese()+"\n");
        this.orderReviewTextArea.append("Size: "+pizza.get_size()+"\n");
        this.orderReviewTextArea.append("Crust: "+pizza.get_crust()+"\n");
        this.orderReviewTextArea.append("Toppings: "+pizza.get_toppings()+"\n");
        this.orderReviewTextArea.append("\n");
        this.orderReviewTextArea.append(PizzaOrder.Order(pizza));
        //Append the message for pickup if the user selected the pickupRadioButton
        if(pickupRadioButton.isSelected()){
            this.orderReviewTextArea.append("\n");
            this.orderReviewTextArea.append(PizzaOrder.Pickup());
        }
        //Append the message for delivery if the user selected the deliveryRadioButton
        else if (deliveryRadioButton.isSelected()){
            String orderAddress;
            orderAddress = (String)JOptionPane.showInputDialog(frame, "Enter Address:","Order Address", JOptionPane.PLAIN_MESSAGE, icon, null, null);
            this.orderReviewTextArea.append("\n");
            this.orderReviewTextArea.append(PizzaOrder.Deliver(orderName, orderAddress));
        }
    }//GEN-LAST:event_OrderButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OrderButton;
    private javax.swing.JButton addToppingButton;
    private javax.swing.JLabel addToppingLabel;
    private javax.swing.JTextField addToppingTextField;
    private javax.swing.JTextArea availableToppingTextArea;
    private javax.swing.JLabel availableToppingsLabel;
    private javax.swing.JRadioButton boringRadioButton;
    private javax.swing.ButtonGroup cheeseButtonGroup;
    private javax.swing.JLabel cheesesLabel;
    private javax.swing.JRadioButton cheesyRadioButton;
    private javax.swing.JRadioButton crazyRadioButton;
    private javax.swing.ButtonGroup crustButtonGroup;
    private javax.swing.JLabel crustLabel;
    private javax.swing.ButtonGroup deliveryButtonGroup;
    private javax.swing.JRadioButton deliveryRadioButton;
    private javax.swing.JRadioButton fetaRadioButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton kidsRadioButton;
    private javax.swing.JRadioButton massiveRadioButton;
    private javax.swing.JRadioButton mozzarrellaRadioButton;
    private javax.swing.JTextArea orderReviewTextArea;
    private javax.swing.JRadioButton pickupRadioButton;
    private javax.swing.JLabel recipeLabel;
    private javax.swing.JRadioButton regularRadioButton;
    private javax.swing.JRadioButton ricottaRadioButton;
    private javax.swing.ButtonGroup sizeButtonGroup;
    private javax.swing.JLabel sizesLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
